# Generated by Django 5.2.1 on 2025-06-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=4)),
                ('code', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('credit', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['subject', 'code'],
                'unique_together': {('subject', 'code')},
            },
        ),
    ]
