# Generated by Django 5.2.1 on 2025-07-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coreqs',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='prereqs',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
